//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public Cours()
        {
            this.CourseUsers = new HashSet<CourseUser>();
            this.StudentGrades = new HashSet<StudentGrade>();
        }
    
        public int Id { get; set; }
        public string SubCode { get; set; }
        public string Level { get; set; }
        public string CourseName { get; set; }
        public int Credit { get; set; }
    
        public virtual ICollection<CourseUser> CourseUsers { get; set; }
        public virtual ICollection<StudentGrade> StudentGrades { get; set; }
    }
}
