//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.RoleTasks = new HashSet<RoleTask>();
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public int Role_ID { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<RoleTask> RoleTasks { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
